version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable  

jobs:
  check_prs:
    executor: base
    steps:
      - run: 
          name: Check PRs
          command: |
            pr_request=`curl --request GET --url https://api.github.com/repos/ryanpedersen42/${CIRCLE_PROJECT_REPONAME}/pulls --header "Authorization: Bearer ${GITHUB_API_TOKEN}" | jq length`
            echo $pr_requests
      - run:
          name: Report
          command: |
            echo "to do"

workflows:
  main:
    jobs:
      - check_prs:
          context:
            - github
