version: 2.1

executors:
  docker:
    - image: cimg/base:stable  

jobs:
  check_prs:
    executor: base
    steps:
      - run: 
          name: Check PRs
          command: |
            curl https://api.github.com/repos/ryanpedersen42/${CIRCLE_PROJECT_REPONAME}/pulls | jq length
      - run:
          name: Report
          command: |
            echo "to do"


workflows:
  main:
    jobs:
      - check_prs
